branches:
  only:
    - master

os: osx
osx_image: xcode10.2
language: swift

env:
  global:
    - XCODE_WORKSPACE="FFCoreData/FFCoreData.xcworkspace"
    - XCODE_SCHEME=FFCoreData
script: ./scripts/build_xcode.sh

jobs:
  include:
    - name: "iOS"
      env: XCODE_DESTINATION="platform=iOS Simulator,OS=12.2,name=iPad Pro (10.5-inch)"
    - name: "macOS"
      env: XCODE_DESTINATION="platform=macOS"
