branches:
  only:
    - master
    - develop
language: swift
os: osx
osx_image: xcode10
xcode_project: FFCoreData/FFCoreData.xcworkspace
xcode_scheme: FFCoreData
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPad Pro (9.7-inch)
