name: Release Processing

on:
  release:
    types:
      - published
      - updated

jobs:
  publish-docs:
    runs-on: macos-latest
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_12.1.app/Contents/Developer
      - uses: dawidd6/action-get-tag@v1
        id: get-tag
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{runner.os}}-spm-${{hashFiles('**/Package.resolved')}}
          restore-keys: |
            ${{runner.os}}-spm-
      - uses: sersoft-gmbh/swifty-docs-action@v1
        with:
          module-version: ${{steps.get-tag.outputs.tag}}
          output: docs
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
